[profile.default]
solc_version = "0.8.18"
via_ir = true

verbosity = 3

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
mumbai = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }

[profile.somewhat_heavy_fuzz.fuzz]
runs = 1000

[profile.heavy_fuzz.fuzz]
runs = 10000

[profile.superheavy_fuzz.fuzz]
runs = 100000
